### ISSUE TITLE
Horizontal scroll bar is too small

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#14]
Horizontal scroll bar is too small when opening wide board like https://issues.stage.jboss.org/download/resources/org.jirban.jirban-jira/webapp/index.html#../../app/board?board=EAPTEST7 

It's like 1 pixel high, I'm using Fedora 23, FF 46 and Chrome 50.

**Comment by kabir** [comment]
On OS X I haven't actually been using the scrollbars at all.What I normally use is 'gesture swiping' in the main pane of the board itself. Is this also available on Fedora, or is it a Mac thing? If it is available on Fedora, is it available with both trackpad and using a mouse?

With the layout I used for the table what I ended up with was a pure CSS mechanism where 
- the vertical scrollbar is only visible if scrolled to the right
- the horizontal scrollbar is only visible if scrolled to the bottom

Since I have gesture swiping, I haven't seen this as a problem. But if this is not available on all platforms, I agree this is a problem and needs changing to use another mechanism.

**Comment by rsvoboda** [comment]
Fedora supports some basics for gesture swiping but definitely it's far from https://support.apple.com/en-us/HT204895
My setup is docking station with external monitor. Mouse and keyboard are external too ... I can swipe them only on the table :)

**Comment by kabir** [comment]
This seems pretty high priority then! I'll look at this next after I finish #7
