### ISSUE TITLE
No login redirection when accessing directly the board

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#22]
When I access directly the board I receive just "You do not appear to be logged in." message.

Redirect the page to the login page when user is not logged in.

Another option is to add more text and link to the root of jira instance - e.g. "You do not appear to be logged in, please log in first and then return back to this board"  and the "log in" would be hyperlink to the URL_OF_JIRA_INSTANCE/login.jsp - for example https://issues.jboss.org/login.jsp

**Comment by kabir** [comment]
I went with the second link option since:
- it was the easiest option
- the user sees what is going on and can act rather than suddenly being taken to a login page. If I knew how to 'decorate' Jira's login page, then we would have had other options. I could probably have created a custom login page as well, but that is harder.

I'll close this issue once it has been uploaded

**Comment by kabir** [comment]
This has been uploaded

**Comment by rsvoboda** [comment]
I'm fine with the fix, thank you.
