### ISSUE TITLE
Make deployed context configurable

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#79]
Introduce possibility to deploy jirban under different context on jira instance. This would enable something like blue/green deployment.

Doing a side-by side deployment would be safer as one does not necessarily have stage/testing JIRA instance or the data are bit different between instances.

**Comment by kabir** [comment]
I think this will be more difficult than when first mentioned. It isn't just a matter of creating a new context root. There are other named things which I think are global:
- The rest urls used by the client
- The names of all the things set up in atlassian-plugin.xml are global to Jira AFAIK
- The keys of things set up in in jirban-jira.properties are global to Jira AFAIK
- The @Named annotations on the injectable beans, e.g https://github.com/jirban/jirban-jira/blob/4088b081713454d6d788bc526a592ade27866755/src/main/java/org/jirban/jira/impl/BoardManagerImpl.java#L60 are also global

There are probably more things too.

One idea is to have a master-stage branch, which replaces all those things in a commit and to keep rebasing that branch on the master branch as things get merged. It would mean that the upstream branch keeps on changing, but since this is a convenience that might be ok. It will basically just be master with extra stuff on top anyway.

Similarly, there are some Jira SDK incompatibilities between our current Jira target 6.4.x and Jira 7.0.x. Once we move to 7.0.x I will need to change master. Perhaps we could use a similar approach to keep a 6.4.x branch going. Although once the scope of the changes is known, it might be easier to just document what the changes were, so people can 'downgrade' themselves - at least until people start demanding it.

**Comment by rsvoboda** [comment]
Extra branch seems to be extra effort. Any possibility for parametrization? 

Or maybe create jar as we do now and just have some automated procedure to hack it and replace the locations ?

**Comment by kabir** [comment]
No plans to do this
